
crop_aliases:
  wheat:
  - wheat_seeds
  beetroot:
  - beetroot_seeds
  - beetroots
  potato:
  - potatoes
  carrot:
  - carrots
  nether_wart:
  - nether_wart_block

click_block_particles:
  period: 32
  nearby: { x: 20.0, y: 8.0, z: 20.0 }
  type: VILLAGER_HAPPY
  count: 20
  spread: { x: 0.5, y: 0.7, z: 0.5 }
  extra: 0
